### ISSUE TITLE
White flashing background when opening the app

### ISSUE THREAD

**Issue by riklus** [pretty-clean/bugs#10] opened 2022-10-16 19:00 UTC
The app flashes a white background on launch.

**Comment by aiyanbo** [comment] 2022-10-17 03:11
Hi, Is your system in dark mode? and your app version is less than 1.0.26?

If your app version is less than 1.0.26, please upgrade first. That has a bug in dark mode.

**Comment by aiyanbo** [comment] 2022-10-17 03:19
Suppose the app does not pop up the upgrade dialog. Please download the latest version at https://www.prettyclean.cc.

**Comment by riklus** [comment] 2022-10-26 22:00
https://user-images.githubusercontent.com/82454869/198146640-7154df5f-2fba-4ddc-aa3d-0e83840822e7.mp4

Yes my system uses dark mode, and I have now tested the latest version (PrettyClean_0.1.26_x64).

**Comment by aiyanbo** [comment] 2022-10-27 02:00
@riklus Thanks, I will find the cause and fix it.

**Comment by aiyanbo** [comment] 2022-10-31 06:06
https://github.com/tauri-apps/tauri/issues/1564

**Comment by aiyanbo** [comment] 2022-10-31 06:06
It was fixed in 0.1.27.

**Closed** 2022-10-31 06:06 UTC
Labels: bug
